disabled_rules: # rule identifiers to exclude from running
  - line_length
  - todo
  - trailing_whitespace
  - variable_name
  - void_return
  - colon
  
opt_in_rules:
  - force_unwrapping # error
  
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - fastlane
  - Carpool/Helper/Constants
# parameterized rules can be customized from this configuration file
file_length:
  - 700
  - 1000
line_length:
  - 230
  - 250
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
  - 150 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error
