# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.46.0"

default_platform :ios

platform :ios do
  
  # stages

  before_all do
    
  end  

  after_all do |lane|
    notification(title: "[Fastlane]", message: "Completed #{lane} lane!")
  end

  error do |lane, exception|
    clean_build_artifacts
    notification(title: "[Fastlane] Lane #{lane} failed to executed!", message: exception.message)
  end

  lane :ensureDevelop do
    # reference: https://docs.fastlane.tools/actions/#source-control
    ensure_git_branch(
      branch: 'develop'
    )
  end

  desc "Push to `origin` remote, `develop` branch"
  lane :gitPushOriginDevelop do 
    ensureDevelop
    push_to_git_remote(
      remote: "origin",         # optional, default: "origin"
      local_branch: "develop",  # optional, aliased by "branch", default: "master"
      remote_branch: "develop", # optional, default is set to local_branch
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
